## These two functions allow for a matrix's inverse to be cached to avoid costly computation.
## The first function creates a special "matrix" object that can cache its inverse (actually a list containing functions and variables).
## The second function tests if the inverse is in the cache and returns the result. 
## If not in cache already, this function performs the calculation and stores it in cache.

## The makeCacheMatrix() function takes a matrix input and creates a list containing 4 functions to:
## 1. set the value of the matrix
## 2. get the value of the matrix
## 3. set the value of the inverse
## 4. get the value of the inverse

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL ## Clears the cache (m).
  set <- function(y) { ## Defines a function set() which stores input into x in the parent environment, and clears the cache (m).
    x <<- y
    m <<- NULL
  }
  get <- function() x ## Defines a function get() that gets the value of x
  setinv <- function(inv) m <<- inv ## Defines a function setinv() that takes an input and stores it in m (the cache) in the parent environment. {m <<- inv} is the function, we just don't need brackets here.
  getinv <- function() m ## Defines a function getinv() which calls m (the cache)
  ## Puts these functions into a list so they can be called using $ followed by the function name ($ is used to extract elements of a list or data frame by name)
  list(set = set, get = get, 
       setinv = setinv,
       getinv = getinv)
} 

## The cacheSolve() function takes the "matrix" generated by makeCacheMatrix() as its input and
## checks the cache to see if the inverse of the set matrix has been calculated and stored previously.
## If the cache exists, this function returns the inverse from the cache. 
## If the cache is empty, this functions performs the solve function to get the inverse, returns it, and stores the result in cache.

cacheSolve <- function(x, ...) {
  m <- x$getinv() ##gets inverse from the cache and stores in local variable m. 
  if(!is.null(m)) { ##if m exists (is not NULL), print "getting cached data" and return the cached data.
    message("getting cached data")
    return(m)
  }
  data <- x$get() ## If m is NULL (inverse not yet cached), gets the original matrix and store it locally in "data".
  m <- solve(data, ...) ## Take the inverse of data and store locally in m.
  x$setinv(m) ## Store the inverse in the cache using the setinv() function defined in line 19.
  m      ## Returns the inverse matrix.
}
